import type { Level } from '@/types'

export const sampleLevels: Omit<Level, 'id' | 'class_id'>[] = [
  // ─── Match Challenges (1–9) ───────────────────────────────────────────────
  {
    level_number: 1,
    description: '**Anchors** — Use `^` and `$` to match the exact word "cat".',
    pattern: '^cat$',
    test_cases: [
      { string: 'cat', shouldMatch: true },
      { string: 'cats', shouldMatch: false },
      { string: 'catapult', shouldMatch: false },
      { string: 'dog', shouldMatch: false },
      { string: 'c at', shouldMatch: false },
    ],
  },
  {
    level_number: 2,
    description: '**The Dot Wildcard** — Use `.` to match any single character. Match "cat", "cot", and "cut".',
    pattern: 'c.t',
    test_cases: [
      { string: 'cat', shouldMatch: true },
      { string: 'cot', shouldMatch: true },
      { string: 'cut', shouldMatch: true },
      { string: 'ct', shouldMatch: false },
      { string: 'cart', shouldMatch: false },
    ],
  },
  {
    level_number: 3,
    description: '**Digit Matching** — Use `\\d` to match any digit. Match strings containing a digit.',
    pattern: '\\d',
    test_cases: [
      { string: '1', shouldMatch: true },
      { string: 'abc', shouldMatch: false },
      { string: 'room 101', shouldMatch: true },
      { string: 'hello', shouldMatch: false },
      { string: '99 bottles', shouldMatch: true },
    ],
  },
  {
    level_number: 4,
    description: '**Character Sets** — Use `[aeiou]` to match any vowel letter.',
    pattern: '[aeiou]',
    test_cases: [
      { string: 'apple', shouldMatch: true },
      { string: 'sky', shouldMatch: false },
      { string: 'hello', shouldMatch: true },
      { string: 'why', shouldMatch: false },
      { string: 'music', shouldMatch: true },
    ],
  },
  {
    level_number: 5,
    description: '**Optional Quantifier** — Use `?` to make the `u` optional. Match both "color" and "colour".',
    pattern: 'colou?r',
    test_cases: [
      { string: 'color', shouldMatch: true },
      { string: 'colour', shouldMatch: true },
      { string: 'colouur', shouldMatch: false },
      { string: 'colr', shouldMatch: false },
      { string: 'coolor', shouldMatch: false },
    ],
  },
  {
    level_number: 6,
    description: '**One or More** — Use `+` to match one or more digits.',
    pattern: '\\d+',
    test_cases: [
      { string: '42', shouldMatch: true },
      { string: '7', shouldMatch: true },
      { string: 'abc', shouldMatch: false },
      { string: '', shouldMatch: false },
      { string: '2024', shouldMatch: true },
    ],
  },
  {
    level_number: 7,
    description: '**Alternation** — Use `|` to match either "yes" or "no".',
    pattern: '^(yes|no)$',
    test_cases: [
      { string: 'yes', shouldMatch: true },
      { string: 'no', shouldMatch: true },
      { string: 'maybe', shouldMatch: false },
      { string: 'YES', shouldMatch: false },
      { string: 'no no', shouldMatch: false },
    ],
  },
  {
    level_number: 8,
    description: '**Email** — Match a simple email address using `\\S+@\\S+`.',
    pattern: '\\S+@\\S+',
    test_cases: [
      { string: 'user@example.com', shouldMatch: true },
      { string: 'name@domain.org', shouldMatch: true },
      { string: 'not-an-email', shouldMatch: false },
      { string: '@missing.com', shouldMatch: false },
      { string: 'spaces in email@x.com', shouldMatch: false },
    ],
  },
  {
    level_number: 9,
    description: '**Phone Number** — Match a US phone number like `555-123-4567` using `\\d{3}-\\d{3}-\\d{4}`.',
    pattern: '\\d{3}-\\d{3}-\\d{4}',
    test_cases: [
      { string: '555-123-4567', shouldMatch: true },
      { string: 'call 800-555-0199 now', shouldMatch: true },
      { string: '1234567890', shouldMatch: false },
      { string: '555-12-34567', shouldMatch: false },
      { string: '555-1234-567', shouldMatch: false },
    ],
  },

  // ─── Find & Replace Challenges (10–50) ────────────────────────────────────
  {
    level_number: 10,
    description: '**Collapse Whitespace** — Replace one or more whitespace characters with a single space using `\\s+`.',
    pattern: '',
    test_cases: [],
    buffer: 'hello    world\nfoo   bar\none  two',
    expected: 'hello world\nfoo bar\none two',
  },
  {
    level_number: 11,
    description: '**Strip HTML Tags** — Remove all HTML tags using `<[^>]+>`. Leave the replacement empty.',
    pattern: '',
    test_cases: [],
    buffer: '<b>hello</b>\n<i>world</i>\n<span>regex</span>',
    expected: 'hello\nworld\nregex',
  },
  {
    level_number: 12,
    description: '**Bold Words** — Wrap each word in `<b>` tags using a capturing group `(\\w+)` and `$1` in the replacement.',
    pattern: '',
    test_cases: [],
    buffer: 'hello\nworld\nregex',
    expected: '<b>hello</b>\n<b>world</b>\n<b>regex</b>',
  },
  {
    level_number: 13,
    description: '**US to EU Date** — Swap month and day using `(\\d{2})/(\\d{2})/(\\d{4})` and replace with `$2/$1/$3`.',
    pattern: '',
    test_cases: [],
    buffer: '03/15/2024\n12/25/2024\n01/01/2025',
    expected: '15/03/2024\n25/12/2024\n01/01/2025',
  },
  {
    level_number: 14,
    description: '**Quote Words** — Wrap each word in double quotes using `(\\w+)` and `"$1"`.',
    pattern: '',
    test_cases: [],
    buffer: 'hello world\nfoo bar',
    expected: '"hello" "world"\n"foo" "bar"',
  },
  {
    level_number: 15,
    description: '**Remove Line Numbers** — Each line starts with a number and a period. Remove them using `^\\d+\\.\\s*` with the multiline flag. Use `/pattern/flags` syntax.',
    pattern: '',
    test_cases: [],
    buffer: '1. first\n2. second\n3. third',
    expected: 'first\nsecond\nthird',
  },
  {
    level_number: 16,
    description: '**Swap CSV Columns** — A CSV has two columns separated by a comma. Swap them using `(\\w+),(\\w+)` and `$2,$1`.',
    pattern: '',
    test_cases: [],
    buffer: 'name,age\ncity,zip',
    expected: 'age,name\nzip,city',
  },
  {
    level_number: 17,
    description: '**Extract Domain** — Extract the domain from email addresses using `@(\\S+)` and `$1`.',
    pattern: '',
    test_cases: [],
    buffer: 'user@gmail.com\nadmin@example.org\ntest@yahoo.com',
    expected: 'gmail.com\nexample.org\nyahoo.com',
  },
  {
    level_number: 18,
    description: '**Add List Markers** — Add `"- "` at the start of every line using `^` (multiline) or wrap each word. Use `/^/gm` with `- ` as replacement.',
    pattern: '',
    test_cases: [],
    buffer: 'apple\nbanana\ncherry',
    expected: '- apple\n- banana\n- cherry',
  },
  {
    level_number: 19,
    description: '**Remove Comments** — Remove `//` comments from code lines. Use `//.*` and empty replacement.',
    pattern: '',
    test_cases: [],
    buffer: 'let x = 1; // set x\nlet y = 2; // set y\nlet z = 3;',
    expected: 'let x = 1; \nlet y = 2; \nlet z = 3;',
  },
  {
    level_number: 20,
    description: '**Extract Filenames** — Extract filenames from Unix paths using `/(\\S+)$` or `/(\\w+\\.\\w+)$`.',
    pattern: '',
    test_cases: [],
    buffer: '/home/user/documents/report.txt\n/var/log/system.log\n/tmp/data.csv',
    expected: 'report.txt\nsystem.log\ndata.csv',
  },
  {
    level_number: 21,
    description: '**Wrap in Parentheses** — Wrap each word in parentheses using `(\\w+)` and `($1)`.',
    pattern: '',
    test_cases: [],
    buffer: 'cat dog bird',
    expected: '(cat) (dog) (bird)',
  },
  {
    level_number: 22,
    description: '**Markdown to HTML Headings** — Convert `# Heading` to `<h1>Heading</h1>` using `^# (.*)` and `<h1>$1</h1>`. Use multiline flag.',
    pattern: '',
    test_cases: [],
    buffer: '# Title\n## Subtitle\n### Section',
    expected: '<h1>Title</h1>\n<h2>Subtitle</h2>\n<h3>Section</h3>',
  },
  {
    level_number: 23,
    description: '**Phone Format** — Convert `5551234567` to `(555) 123-4567` using `(\\d{3})(\\d{3})(\\d{4})` and `($1) $2-$3`.',
    pattern: '',
    test_cases: [],
    buffer: '5551234567\n8005550199',
    expected: '(555) 123-4567\n(800) 555-0199',
  },
  {
    level_number: 24,
    description: '**Remove Empty Lines** — Remove lines that contain only whitespace using `^\\s*$\\n?` and empty replacement.',
    pattern: '',
    test_cases: [],
    buffer: 'hello\n\nworld\n\nfoo\n\n\nbar',
    expected: 'hello\nworld\nfoo\nbar',
  },
  {
    level_number: 25,
    description: '**Sort Words** — Sort words on each line alphabetically. This is a challenge that requires multiple find+replace passes or a clever pattern.',
    pattern: '',
    test_cases: [],
    buffer: 'banana apple\nzebra yak xray',
    expected: 'apple banana\nxray yak zebra',
  },
  {
    level_number: 26,
    description: '**Snake to Camel** — Convert snake_case to camelCase using `_(.)` and uppercase replacement. In JS, use a function or this trick: find `_(\\w)` and replace with just the letter (then it stays lowercase). Alternatively, find `(\\w+)_` and replace with nothing to remove the first part.',
    pattern: '',
    test_cases: [],
    buffer: 'first_name\nlast_name\nuser_id',
    expected: 'firstName\nlastName\nuserId',
  },
  {
    level_number: 27,
    description: '**Markdown Links** — Convert markdown links `[text](url)` to HTML `<a href="url">text</a>` using `\\[([^\\]]+)\\]\\(([^)]+)\\)`.',
    pattern: '',
    test_cases: [],
    buffer: '[Google](https://google.com)\n[GitHub](https://github.com)',
    expected: '<a href="https://google.com">Google</a>\n<a href="https://github.com">GitHub</a>',
  },
  {
    level_number: 28,
    description: '**Extract Hashtags** — Extract hashtags from social media posts using `#(\\w+)` and `$1`.',
    pattern: '',
    test_cases: [],
    buffer: 'Love #coding and #regex\nCheck out #javascript #webdev',
    expected: 'coding\nregex\njavascript\nwebdev',
  },
  {
    level_number: 29,
    description: '**CSV to HTML Table Row** — Convert CSV lines to HTML table rows using `([^,]+),([^,]+),([^,]+)` and `<tr><td>$1</td><td>$2</td><td>$3</td></tr>`.',
    pattern: '',
    test_cases: [],
    buffer: 'John,30,NYC\nJane,25,LA',
    expected: '<tr><td>John</td><td>30</td><td>NYC</td></tr>\n<tr><td>Jane</td><td>25</td><td>LA</td></tr>',
  },
  {
    level_number: 30,
    description: '**Currency Format** — Add `$` prefix to all numbers using `(\\d+)` and `$$$1`.',
    pattern: '',
    test_cases: [],
    buffer: 'item costs 5\nprice is 100',
    expected: 'item costs $5\nprice is $100',
  },
  {
    level_number: 31,
    description: '**Remove Vowels** — Remove all vowels from the text using `[aeiou]` (case-insensitive flag `i`). Use `/[aeiou]/gi` with empty replacement.',
    pattern: '',
    test_cases: [],
    buffer: 'Hello World\nRegex Is Fun',
    expected: 'Hll Wrld\nRgx s Fn',
  },
  {
    level_number: 32,
    description: '**Reverse Words** — Reverse each line using `(\\w+) (\\w+)` and `$2 $1`.',
    pattern: '',
    test_cases: [],
    buffer: 'hello world\nfoo bar',
    expected: 'world hello\nbar foo',
  },
  {
    level_number: 33,
    description: '**Mask Passwords** — Mask all characters after `password=` using `password=(\\S+)` and `password=********`.',
    pattern: '',
    test_cases: [],
    buffer: 'user=admin&password=secret123\nuser=guest&password=letmein',
    expected: 'user=admin&password=********\nuser=guest&password=********',
  },
  {
    level_number: 34,
    description: '**Extract Year** — Extract 4-digit years from text using `(\\d{4})` and `$1`.',
    pattern: '',
    test_cases: [],
    buffer: 'Born in 1990, graduated in 2012\nFirst release in 2020',
    expected: '1990\n2012\n2020',
  },
  {
    level_number: 35,
    description: '**Convert Tabs to Spaces** — Replace all tab characters `\\t` with 4 spaces.',
    pattern: '',
    test_cases: [],
    buffer: 'hello\tworld\nfoo\tbar',
    expected: 'hello    world\nfoo    bar',
  },
  {
    level_number: 36,
    description: '**Markdown Checkbox** — Convert `- [ ]` to `✗` and `- [x]` to `✓`. Use two separate replacements. First find `- \\[x\\]` replace with `✓`, then find `- \\[\\]` replace with `✗`.',
    pattern: '',
    test_cases: [],
    buffer: '- [x] learn regex\n- [ ] practice\n- [ ] build app',
    expected: '✓ learn regex\n✗ practice\n✗ build app',
  },
  {
    level_number: 37,
    description: '**Extract Hex Colors** — Extract hex color codes using `(#[0-9a-fA-F]{3,6})` and `$1`.',
    pattern: '',
    test_cases: [],
    buffer: 'color: #ff0000;\nbackground: #abc;\nborder: #a1b2c3;',
    expected: '#ff0000\n#abc\n#a1b2c3',
  },
  {
    level_number: 38,
    description: '**Camel to Snake** — Convert camelCase to snake_case using `([a-z])([A-Z])` and `$1_$2`, then lowercase everything. Try it in two passes.',
    pattern: '',
    test_cases: [],
    buffer: 'firstName\nlastName\nuserId',
    expected: 'first_name\nlast_name\nuser_id',
  },
  {
    level_number: 39,
    description: '**XML to Self-Closing** — Convert `<tag></tag>` to `<tag/>` using `<(\\w+)></\\1>` and `<$1/>`.',
    pattern: '',
    test_cases: [],
    buffer: '<div></div>\n<span></span>\n<p>text</p>',
    expected: '<div/>\n<span/>\n<p>text</p>',
  },
  {
    level_number: 40,
    description: '**Sort CSV by First Column** — Sort the CSV lines alphabetically by the first field. This requires careful find+replace or manual sorting.',
    pattern: '',
    test_cases: [],
    buffer: 'banana,yellow\napple,red\ncherry,dark red',
    expected: 'apple,red\nbanana,yellow\ncherry,dark red',
  },
  {
    level_number: 41,
    description: '**Wrap Lines in List Item** — Wrap each line in `<li>` tags using `^(.*)$` and `<li>$1</li>`. Use multiline flag.',
    pattern: '',
    test_cases: [],
    buffer: 'apple\nbanana\ncherry',
    expected: '<li>apple</li>\n<li>banana</li>\n<li>cherry</li>',
  },
  {
    level_number: 42,
    description: '**Format Time** — Convert `HH:MM:SS` to `HH hours MM minutes SS seconds` using `(\\d{2}):(\\d{2}):(\\d{2})` and `$1 hours $2 minutes $3 seconds`.',
    pattern: '',
    test_cases: [],
    buffer: '14:30:00\n09:15:30',
    expected: '14 hours 30 minutes 00 seconds\n09 hours 15 minutes 30 seconds',
  },
  {
    level_number: 43,
    description: '**Markdown Bold to HTML** — Convert `**text**` to `<strong>text</strong>` using `\\*\\*([^*]+)\\*\\*` and `<strong>$1</strong>`.',
    pattern: '',
    test_cases: [],
    buffer: 'This is **bold** text\n**very** important',
    expected: 'This is <strong>bold</strong> text\n<strong>very</strong> important',
  },
  {
    level_number: 44,
    description: '**Extract URL Paths** — Extract the path from URLs using `https?://[^/]+(/\\S*)` and `$1`.',
    pattern: '',
    test_cases: [],
    buffer: 'https://example.com/docs/guide\nhttps://api.site.com/v1/users',
    expected: '/docs/guide\n/v1/users',
  },
  {
    level_number: 45,
    description: '**Number Lines** — Add line numbers to each line using `^(.*)$` and `$1. $2` where you need to track the line number. This is tricky with regex alone.',
    pattern: '',
    test_cases: [],
    buffer: 'first\nsecond\nthird',
    expected: '1. first\n2. second\n3. third',
  },
  {
    level_number: 46,
    description: '**Remove Duplicate Words** — Remove consecutive duplicate words using `(\\b\\w+\\b)\\s+\\1` and `$1`.',
    pattern: '',
    test_cases: [],
    buffer: 'the the quick brown fox jumps over the lazy dog',
    expected: 'the quick brown fox jumps over the lazy dog',
  },
  {
    level_number: 47,
    description: '**Markdown Italic** — Convert `*text*` to `<em>text</em>` using `\\*([^*]+)\\*` and `<em>$1</em>`.',
    pattern: '',
    test_cases: [],
    buffer: 'This is *italic* text\n*very* nice',
    expected: 'This is <em>italic</em> text\n<em>very</em> nice',
  },
  {
    level_number: 48,
    description: "**SQL Values to CSV** — Convert `('val1', 'val2', 'val3')` to `val1,val2,val3` using `\\('([^']*)'\\)` and `$1`.",
    pattern: '',
    test_cases: [],
    buffer: "('John', '30', 'NYC')\n('Jane', '25', 'LA')",
    expected: 'John,30,NYC\nJane,25,LA',
  },
  {
    level_number: 49,
    description: '**Extract JSON Keys** — Extract keys from simple JSON using `"(\\w+)":` and `$1`.',
    pattern: '',
    test_cases: [],
    buffer: '{"name": "John", "age": 30, "city": "NYC"}',
    expected: 'name\nage\ncity',
  },
  {
    level_number: 50,
    description: '**Final Boss** — Convert a markdown table to HTML `<table>`. Use multiple find+replace passes. First split header and rows, then convert each line.',
    pattern: '',
    test_cases: [],
    buffer: '| Name | Age | City |\n|------|-----|------|\n| John | 30 | NYC |\n| Jane | 25 | LA |',
    expected: '<table>\n<tr><th>Name</th><th>Age</th><th>City</th></tr>\n<tr><td>John</td><td>30</td><td>NYC</td></tr>\n<tr><td>Jane</td><td>25</td><td>LA</td></tr>\n</table>',
  },
]
